#!/usr/bin/env bash
# scripts/smoke/package-smoke.sh
#
# Package smoke: assert first-contact contracts through the real npm entry point.
# The tarball is installed INTO the fixture projects and every CLI invocation goes
# through `npx --no-install specrunner` — the exact command an npm user types —
# so the package `bin` wiring, shebang, and `.bin/specrunner` generation are all
# on the asserted path. No bun. No src/ references.
#
# Local run: bash scripts/smoke/package-smoke.sh
#
# What it does:
#   1. Verifies dist/specrunner.js exists (build first if not)
#   2. npm pack → installs the tarball into fixture projects
#   3. Runs assertion scenarios via `npx --no-install specrunner`
#   4. Cleans up all temp dirs on exit via trap
#
# Scenarios (all through the npx bin entry):
#   S5  : --help exits 0 AND prints usage (bin wiring / shebang / usage output)
#   S1  : init outside a git repository (non-git install dir) exits non-zero, writes nothing
#   S2  : first init from a nested subdirectory lands scaffold at repo root,
#         per-item "created" report
#   S2b : second init reports per-item "already exists" (idempotent)
#   S2c : half-initialized repo (config kept, scaffold removed) → per-item
#         created / already-exists split
#   S3  : doctor --json from root AND subdirectory produce identical per-check
#         results, and config-file-exists = pass under isolated XDG
#         (per-check judgment, not exit code)
#   S4  : request new from a nested subdirectory lands at repo root without nesting
#
# Hermeticity: every invocation uses isolated HOME / XDG_CONFIG_HOME under mktemp;
# ambient tokens or real user config never affect the assertions.

set -u

# ── Repo root resolution ─────────────────────────────────────────────────────
# SMOKE_REPO_ROOT override allows tests to point to a directory without dist
# (e.g. for the dist-precheck unit test) without affecting the real repo root.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${SMOKE_REPO_ROOT:-$(cd "${SCRIPT_DIR}/../.." && pwd)}"

# ── Pre-check: dist must exist ───────────────────────────────────────────────
# The smoke script does NOT build — it asserts the already-built artifact.
DIST_PATH="${REPO_ROOT}/dist/specrunner.js"
if [ ! -f "${DIST_PATH}" ]; then
  echo "ERROR: dist/specrunner.js not found at ${DIST_PATH}" >&2
  echo "Run 'bun run build' first to generate the dist bundle before running the smoke." >&2
  echo "(This script does not invoke bun — build separately then re-run.)" >&2
  exit 1
fi

# ── Temp dir management ──────────────────────────────────────────────────────
SMOKE_TMP="$(mktemp -d)"
PACK_DIR="$(mktemp -d)"

cleanup() {
  rm -rf "${SMOKE_TMP}" "${PACK_DIR}"
}
trap cleanup EXIT

# ── Pack the tarball ─────────────────────────────────────────────────────────
(cd "${REPO_ROOT}" && npm pack --pack-destination "${PACK_DIR}" >/dev/null 2>&1)
TARBALL="$(ls "${PACK_DIR}"/*.tgz 2>/dev/null | head -1)"
if [ -z "${TARBALL}" ]; then
  echo "ERROR: npm pack did not produce a .tgz file in ${PACK_DIR}" >&2
  exit 1
fi

# ── Fixture setup ────────────────────────────────────────────────────────────
# F1: non-git install dir (for S1 — init outside a repository, still via npx)
# F2: fixture git repo with the tarball installed as a dev dependency (S2–S5)
F1_DIR="${SMOKE_TMP}/nogit-app"
F2_REPO="${SMOKE_TMP}/fixture-repo"
F2_SUB="${F2_REPO}/sub/deep"
mkdir -p "${F1_DIR}" "${F2_SUB}"

(cd "${F1_DIR}" && npm init -y >/dev/null 2>&1 && npm install --omit=optional "${TARBALL}" >/dev/null 2>&1)
(cd "${F2_REPO}" && npm init -y >/dev/null 2>&1 && npm install --omit=optional "${TARBALL}" >/dev/null 2>&1)
git -C "${F2_REPO}" init --quiet 2>/dev/null
git -C "${F2_REPO}" config user.email "smoke@example.com" 2>/dev/null
git -C "${F2_REPO}" config user.name "Smoke Test" 2>/dev/null
# Origin stub: makes the fixture shape match a real project (URL only — never contacted).
git -C "${F2_REPO}" remote add origin "https://github.com/example/fixture-app.git" 2>/dev/null

# The npm-generated bin symlink is itself part of the asserted surface: if the
# package `bin` field or the dist shebang breaks, this precondition (and every
# npx invocation below) fails.
for d in "${F1_DIR}" "${F2_REPO}"; do
  if [ ! -e "${d}/node_modules/.bin/specrunner" ]; then
    echo "ERROR: ${d}/node_modules/.bin/specrunner was not generated by npm install" >&2
    echo "package.json bin wiring may be broken." >&2
    exit 1
  fi
done

# Isolated env homes. F2 scenarios share one XDG so S2's init provides the
# config that S2b / S2c / S3 build upon (mirrors a real user's sequential session).
S1_XDG="${SMOKE_TMP}/s1-xdg";  S1_HOME="${SMOKE_TMP}/s1-home"
F2_XDG="${SMOKE_TMP}/f2-xdg";  F2_HOME="${SMOKE_TMP}/f2-home"
mkdir -p "${S1_XDG}" "${S1_HOME}" "${F2_XDG}" "${F2_HOME}"

# run_cli <dir> <home> <xdg> <args...> — run `npx --no-install specrunner …`
# from the given directory with env isolation. This is the real npm user entry
# (bin symlink + shebang + upward node_modules resolution).
run_cli() {
  local dir="$1" home="$2" xdg="$3"
  shift 3
  (cd "${dir}" && HOME="${home}" XDG_CONFIG_HOME="${xdg}" GIT_CEILING_DIRECTORIES="${SMOKE_TMP}" \
    npx --no-install specrunner "$@" < /dev/null)
}

# ── Assertion helpers ────────────────────────────────────────────────────────
FAIL_COUNT=0
PASS_COUNT=0

pass() {
  local scenario="$1" detail="${2:-}"
  printf "[SMOKE] PASS  scenario=%-34s %s\n" "${scenario}" "${detail}"
  PASS_COUNT=$((PASS_COUNT + 1))
}

fail() {
  local scenario="$1" detail="${2:-}"
  printf "[SMOKE] FAIL  scenario=%-34s %s\n" "${scenario}" "${detail}" >&2
  FAIL_COUNT=$((FAIL_COUNT + 1))
}

assert_exit_nonzero() {
  local scenario="$1" actual="$2"
  if [ "${actual}" -ne 0 ]; then
    pass "${scenario}" "exit=${actual} (non-zero as expected)"
  else
    fail "${scenario}" "expected non-zero exit, got 0"
  fi
}

assert_exit_zero() {
  local scenario="$1" actual="$2"
  if [ "${actual}" -eq 0 ]; then
    pass "${scenario}" "exit=0"
  else
    fail "${scenario}" "expected exit 0, got ${actual}"
  fi
}

assert_absent() {
  local scenario="$1" path="$2"
  if [ ! -e "${path}" ]; then
    pass "${scenario}" "absent: ${path##*/}"
  else
    fail "${scenario}" "expected absent but found: ${path}"
  fi
}

assert_present() {
  local scenario="$1" path="$2"
  if [ -e "${path}" ]; then
    pass "${scenario}" "present: ${path##*/}"
  else
    fail "${scenario}" "expected present but missing: ${path}"
  fi
}

assert_contains() {
  local scenario="$1" text="$2" pattern="$3"
  if printf '%s' "${text}" | grep -qF "${pattern}"; then
    pass "${scenario}" "output contains '${pattern}'"
  else
    fail "${scenario}" "output missing '${pattern}'"
  fi
}

# ── S5: --help via the npx bin entry — exit 0 AND usage output ───────────────
echo ""
echo "=== S5: npx specrunner --help (bin wiring + usage output) ==="
S5_OUT="$(run_cli "${F2_REPO}" "${F2_HOME}" "${F2_XDG}" --help 2>&1)"; S5_EXIT=$?
assert_exit_zero "S5/help-exit" "${S5_EXIT}"
assert_contains "S5/help-usage" "${S5_OUT}" "Usage: specrunner"

# ── S1: init outside a git repository (via npx from the non-git install) ─────
echo ""
echo "=== S1: init outside a git repo ==="
if GIT_CEILING_DIRECTORIES="${SMOKE_TMP}" git -C "${F1_DIR}" rev-parse --git-dir >/dev/null 2>&1; then
  fail "S1/env-guard" "fixture appears to be inside a git repo — environment issue"
else
  run_cli "${F1_DIR}" "${S1_HOME}" "${S1_XDG}" init --provider anthropic \
    > "${SMOKE_TMP}/s1-stdout.txt" 2>"${SMOKE_TMP}/s1-stderr.txt"; S1_EXIT=$?
  assert_exit_nonzero "S1/exit-nonzero" "${S1_EXIT}"
  assert_absent "S1/no-specrunner-dir" "${F1_DIR}/specrunner"
  assert_absent "S1/no-gitignore" "${F1_DIR}/.gitignore"
  assert_absent "S1/no-xdg-config" "${S1_XDG}/specrunner/config.json"
fi

# ── S2: first init from a nested subdirectory — root landing + per-item report ─
echo ""
echo "=== S2: first init from subdirectory (per-item created report) ==="
S2_OUT="$(run_cli "${F2_SUB}" "${F2_HOME}" "${F2_XDG}" init --provider anthropic 2>&1)"; S2_EXIT=$?
assert_exit_zero "S2/exit-zero" "${S2_EXIT}"
assert_present "S2/root-drafts" "${F2_REPO}/specrunner/drafts"
assert_present "S2/root-changes" "${F2_REPO}/specrunner/changes"
assert_absent "S2/no-nested-specrunner" "${F2_SUB}/specrunner"
assert_contains "S2/report-config" "${S2_OUT}" "global config: created"
assert_contains "S2/report-gitignore" "${S2_OUT}" ".gitignore: created"
assert_contains "S2/report-drafts" "${S2_OUT}" "specrunner/drafts: created"
assert_contains "S2/report-changes" "${S2_OUT}" "specrunner/changes: created"

# ── S2b: second init — per-item already-exists report (idempotent) ───────────
echo ""
echo "=== S2b: second init (per-item already-exists report) ==="
S2B_OUT="$(run_cli "${F2_SUB}" "${F2_HOME}" "${F2_XDG}" init --provider anthropic 2>&1)"; S2B_EXIT=$?
assert_exit_zero "S2b/exit-zero" "${S2B_EXIT}"
assert_contains "S2b/report-config" "${S2B_OUT}" "global config: already exists"
assert_contains "S2b/report-gitignore" "${S2B_OUT}" ".gitignore: already exists"
assert_contains "S2b/report-drafts" "${S2B_OUT}" "specrunner/drafts: already exists"
assert_contains "S2b/report-changes" "${S2B_OUT}" "specrunner/changes: already exists"

# ── S2c: half-initialized repo — created / already-exists split ──────────────
echo ""
echo "=== S2c: half-initialized repo (config kept, scaffold removed) ==="
rm -rf "${F2_REPO}/specrunner" "${F2_REPO}/.gitignore"
S2C_OUT="$(run_cli "${F2_SUB}" "${F2_HOME}" "${F2_XDG}" init --provider anthropic 2>&1)"; S2C_EXIT=$?
assert_exit_zero "S2c/exit-zero" "${S2C_EXIT}"
assert_contains "S2c/report-config-kept" "${S2C_OUT}" "global config: already exists"
assert_contains "S2c/report-gitignore" "${S2C_OUT}" ".gitignore: created"
assert_contains "S2c/report-drafts" "${S2C_OUT}" "specrunner/drafts: created"
assert_contains "S2c/report-changes" "${S2C_OUT}" "specrunner/changes: created"

# ── S3: doctor --json from root AND subdirectory — identical results + XDG pass ─
echo ""
echo "=== S3: doctor --json root/subdirectory equivalence + config-file-exists pass ==="
run_cli "${F2_REPO}" "${F2_HOME}" "${F2_XDG}" doctor --json \
  > "${SMOKE_TMP}/s3-doctor-root.json" 2>/dev/null || true
run_cli "${F2_SUB}" "${F2_HOME}" "${F2_XDG}" doctor --json \
  > "${SMOKE_TMP}/s3-doctor-sub.json" 2>/dev/null || true

S3_VERDICT="$(node -e "
const fs = require('fs');
function checks(p) {
  const data = JSON.parse(fs.readFileSync(p, 'utf8'));
  return (data.results || []).map(function(c) { return c.name + '=' + c.status; }).sort();
}
try {
  const root = checks('${SMOKE_TMP}/s3-doctor-root.json');
  const sub = checks('${SMOKE_TMP}/s3-doctor-sub.json');
  const identical = JSON.stringify(root) === JSON.stringify(sub);
  const cfg = root.find(function(e) { return e.startsWith('config-file-exists='); });
  process.stdout.write((identical ? 'identical' : 'DIFFERENT') + '|' + (cfg || 'not-found'));
} catch (e) {
  process.stdout.write('parse-error:' + String(e.message));
}
" 2>/dev/null || echo "node-error")"

S3_IDENTICAL="${S3_VERDICT%%|*}"
S3_CFG="${S3_VERDICT##*|}"
if [ "${S3_IDENTICAL}" = "identical" ]; then
  pass "S3/root-sub-identical" "per-check results identical"
else
  fail "S3/root-sub-identical" "root vs subdirectory differ or parse failed: ${S3_VERDICT}"
fi
if [ "${S3_CFG}" = "config-file-exists=pass" ]; then
  pass "S3/config-file-exists" "per-check status=pass under isolated XDG"
else
  fail "S3/config-file-exists" "expected config-file-exists=pass, got: ${S3_CFG}"
fi

# ── S4: request new from a nested subdirectory — root landing, no nesting ────
echo ""
echo "=== S4: request new from subdirectory ==="
S4_SLUG="smoke-request-fixture"
run_cli "${F2_SUB}" "${F2_HOME}" "${F2_XDG}" request new "${S4_SLUG}" \
  > /dev/null 2>&1; S4_EXIT=$?
assert_exit_zero "S4/exit-zero" "${S4_EXIT}"
assert_present "S4/root-request-md" "${F2_REPO}/specrunner/drafts/${S4_SLUG}/request.md"
assert_absent "S4/no-nested-specrunner" "${F2_SUB}/specrunner"

# ── Summary ──────────────────────────────────────────────────────────────────
echo ""
echo "=== Smoke summary ==="
echo "PASS: ${PASS_COUNT}  FAIL: ${FAIL_COUNT}"
echo ""

if [ "${FAIL_COUNT}" -gt 0 ]; then
  echo "[SMOKE] RESULT: FAIL  (${FAIL_COUNT} assertion(s) failed)" >&2
  exit 1
else
  echo "[SMOKE] RESULT: PASS  (all ${PASS_COUNT} assertions passed)"
  exit 0
fi
