/**
 * renderAttestationMarkdown — pure function to render an Attestation as a
 * standalone Markdown document suitable for committing to the feature branch.
 *
 * Used for GitHub-integration-disabled jobs: the attestation is written to
 * `specrunner/changes/<slug>/attestation.md` in the feature branch instead
 * of being posted as a PR comment.
 *
 * Shares template structure with renderAttestationComment (same data, similar
 * layout) but avoids GitHub-flavored <details> folding and PR-comment idioms.
 *
 * Pure: no I/O, no side effects.
 */
import { formatUsd } from "../usage/pricing.js";
import type { Attestation } from "./types.js";

/**
 * Render an Attestation as a standalone Markdown document.
 */
export function renderAttestationMarkdown(attestation: Attestation): string {
  const lines: string[] = [];

  lines.push("# SpecRunner Attestation");
  lines.push("");
  lines.push("> Generated by specrunner. This file records the pipeline run outcome.");
  lines.push("");

  // Summary table
  lines.push("## Summary");
  lines.push("");
  lines.push("| Field | Value |");
  lines.push("|-------|-------|");
  lines.push(`| Gates | ${attestation.gates.length} |`);
  lines.push(`| Cost | ${formatUsd(attestation.cost.totalCostUsd)} |`);
  lines.push(`| Journal hash | \`${attestation.journalHash}\` |`);
  lines.push("");

  // Gate history
  if (attestation.gates.length > 0) {
    lines.push("## Gate History");
    lines.push("");
    lines.push("| Step | Attempt | Verdict | Findings |");
    lines.push("|------|---------|---------|----------|");
    for (const gate of attestation.gates) {
      const verdict = gate.verdict ?? "—";
      const findingsCell = gate.findings
        ? `${gate.findings.total} (crit:${gate.findings.bySeverity.critical} high:${gate.findings.bySeverity.high} med:${gate.findings.bySeverity.medium} low:${gate.findings.bySeverity.low})`
        : "—";
      lines.push(`| ${gate.step} | ${gate.attempt} | ${verdict} | ${findingsCell} |`);
    }
    lines.push("");
  }

  // Step models
  if (attestation.stepModels && attestation.stepModels.length > 0) {
    lines.push("## Step Models");
    lines.push("");
    lines.push("| Step | Models |");
    lines.push("|------|--------|");
    for (const sm of attestation.stepModels) {
      lines.push(`| ${sm.step} | ${sm.models.join(", ")} |`);
    }
    lines.push("");
  }

  // Cost breakdown
  const t = attestation.cost.totalTokens;
  lines.push("## Cost Breakdown");
  lines.push("");
  lines.push("| Item | Value |");
  lines.push("|------|-------|");
  lines.push(`| Input tokens | ${t.input.toLocaleString()} |`);
  lines.push(`| Output tokens | ${t.output.toLocaleString()} |`);
  lines.push(`| Cache read tokens | ${t.cacheRead.toLocaleString()} |`);
  lines.push(`| Total cost | ${formatUsd(attestation.cost.totalCostUsd)} |`);
  lines.push("");

  // Machine-readable JSON block
  lines.push("## Machine-Readable Attestation");
  lines.push("");
  lines.push("```json");
  lines.push(JSON.stringify(attestation, null, 2));
  lines.push("```");
  lines.push("");

  return lines.join("\n");
}
