/**
 * T-09: Verify STANDARD_TRANSITIONS has no hardcoded "code-review" step literals.
 *
 * All code-review / code-fixer transition rows must be generated by
 * buildReviewerChainTransitions (no s.steps["code-review"] literals).
 */
import { describe, it, expect } from "vitest";
import { STANDARD_TRANSITIONS } from "../types.js";
import { STEP_NAMES } from "../../step/step-names.js";

describe("STANDARD_TRANSITIONS — code-review rows from buildReviewerChainTransitions", () => {
  it("has code-review transitions", () => {
    const codeReviewRows = STANDARD_TRANSITIONS.filter((t) => t.step === STEP_NAMES.CODE_REVIEW);
    expect(codeReviewRows.length).toBeGreaterThan(0);
  });

  it("has code-fixer transitions", () => {
    const codeFixerRows = STANDARD_TRANSITIONS.filter((t) => t.step === STEP_NAMES.CODE_FIXER);
    expect(codeFixerRows.length).toBeGreaterThan(0);
  });

  it("code-review approved → conformance exists", () => {
    const row = STANDARD_TRANSITIONS.find(
      (t) => t.step === STEP_NAMES.CODE_REVIEW && t.on === "approved" && t.to === STEP_NAMES.CONFORMANCE && !t.when,
    );
    expect(row).toBeDefined();
  });

  it("code-review needs-fix → code-fixer exists", () => {
    const row = STANDARD_TRANSITIONS.find(
      (t) => t.step === STEP_NAMES.CODE_REVIEW && t.on === "needs-fix" && t.to === STEP_NAMES.CODE_FIXER,
    );
    expect(row).toBeDefined();
  });

  it("code-fixer error → escalate exists", () => {
    const row = STANDARD_TRANSITIONS.find(
      (t) => t.step === STEP_NAMES.CODE_FIXER && t.on === "error" && t.to === "escalate",
    );
    expect(row).toBeDefined();
  });

  it("all transitions are objects with step/on/to fields", () => {
    for (const t of STANDARD_TRANSITIONS) {
      expect(typeof t.step).toBe("string");
      expect(typeof t.on).toBe("string");
      expect(typeof t.to).toBe("string");
    }
  });
});

// T-03 (reduce-added-agent-turns): adr-gen skipped transition
describe("STANDARD_TRANSITIONS — adr-gen skipped → pr-create", () => {
  it("adr-gen on 'skipped' transitions to pr-create", () => {
    const row = STANDARD_TRANSITIONS.find(
      (t) => t.step === STEP_NAMES.ADR_GEN && t.on === "skipped" && t.to === STEP_NAMES.PR_CREATE,
    );
    expect(row).toBeDefined();
  });

  it("adr-gen on 'success' still transitions to pr-create (unchanged)", () => {
    const row = STANDARD_TRANSITIONS.find(
      (t) => t.step === STEP_NAMES.ADR_GEN && t.on === "success" && t.to === STEP_NAMES.PR_CREATE,
    );
    expect(row).toBeDefined();
  });

  it("adr-gen on 'error' still escalates (unchanged)", () => {
    const row = STANDARD_TRANSITIONS.find(
      (t) => t.step === STEP_NAMES.ADR_GEN && t.on === "error" && t.to === "escalate",
    );
    expect(row).toBeDefined();
  });
});
