/**
 * lineage-output-attribution: TC-001 through TC-011
 *
 * Verifies that CommitOrchestrator records lineage.outputs paths that correspond
 * to the files ACTUALLY generated by the current attempt (not the next iteration path).
 *
 * Root cause (pre-fix): applySuccessPostPersistEffects evaluated step.writes() on the
 * post-push state (after pushStepResult appended the new StepRun). For iteration-dependent
 * steps this makes nextIteration() return N+1 instead of N — the wrong path (missing file,
 * hash: null).
 *
 * Fix (D1): evaluate writes()/reads() in commitSuccess/commitRound BEFORE calling
 * projectSuccess, then carry the pre-evaluated IoRef[] into applySuccessPostPersistEffects
 * as explicit parameters (preWriteIo, preReadIo).
 *
 * TC IDs are frozen — do not renumber.
 *
 * Affected steps: spec-review, code-review, conformance, request-review, custom-reviewer,
 * regression-gate (all use nextIteration in writes()).
 */

import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import * as os from "node:os";
import * as crypto from "node:crypto";
import { CommitOrchestrator } from "../commit-orchestrator.js";
import { EventBus } from "../../event/event-bus.js";
import { nextIteration } from "../io-iteration.js";
import type { AgentStep } from "../types.js";
import type { JobState, Verdict } from "../../../state/schema.js";
import type { PipelineDeps } from "../../types.js";
import type { StepExecutionResult } from "../commit-orchestrator.js";
import type { StepCompletion } from "../step-completion.js";
import type { LineageRecord } from "../../../store/event-journal.js";
import type { ArtifactRef } from "../../../state/artifact-types.js";

// ---------------------------------------------------------------------------
// Pure helpers
// ---------------------------------------------------------------------------

/** Compute sha256 hex string from content (mirrors LocalRuntime.digestArtifacts). */
function sha256hex(content: string | Buffer): string {
  const buf = typeof content === "string" ? Buffer.from(content) : content;
  return crypto.createHash("sha256").update(buf).digest("hex");
}

// ---------------------------------------------------------------------------
// State / result factories
// ---------------------------------------------------------------------------

function makeState(overrides: Partial<JobState> = {}): JobState {
  return {
    version: 2,
    jobId: "lao-test-job",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z",
    request: {
      path: "specrunner/changes/example/request.md",
      title: "Example",
      type: "bug-fix",
      slug: "example",
    },
    repository: { owner: "octo", name: "repo" },
    session: null,
    step: "iter-step",
    status: "running",
    branch: "fix/example-laotest01",
    history: [],
    error: null,
    steps: {},
    ...overrides,
  };
}

function makeCompletion(verdict: Verdict = "approved"): StepCompletion {
  return { verdict, persistToolResult: null };
}

function makeSuccessResult(
  completion: StepCompletion = makeCompletion(),
): StepExecutionResult & { kind: "success" } {
  return {
    kind: "success",
    completion,
    completedAt: "2026-01-01T00:01:00.000Z",
    startedAt: "2026-01-01T00:00:00.000Z",
    session: null,
  };
}

// ---------------------------------------------------------------------------
// Step mock: iteration-dependent writes()
// ---------------------------------------------------------------------------

/**
 * Build an AgentStep whose writes() calls nextIteration(state, stepName) to compute
 * the output path. This is the exact pattern that causes the off-by-one bug when
 * writes() is evaluated on the post-push state.
 *
 * Used in TC-001, TC-002, TC-003, TC-005, TC-010, TC-011.
 */
function makeIterStep(name = "iter-step"): AgentStep {
  return {
    kind: "agent",
    name,
    agent: { id: `${name}-agent` } as never,
    buildMessage: () => `${name} message`,
    resultFilePath: () => null,
    parseResult: () => ({ verdict: null, findingsPath: null }),
    writes: (state, _deps) => [
      {
        path: `out/result-${nextIteration(state, name).toString().padStart(3, "0")}.md`,
      },
    ],
  };
}

// ---------------------------------------------------------------------------
// Store mock
// ---------------------------------------------------------------------------

interface StoreMock {
  update: ReturnType<typeof vi.fn>;
  appendHistory: ReturnType<typeof vi.fn>;
  fail: ReturnType<typeof vi.fn>;
  persist: ReturnType<typeof vi.fn>;
  appendLineage: ReturnType<typeof vi.fn>;
  appendInterruption: ReturnType<typeof vi.fn>;
}

function makeStoreMock(): StoreMock {
  return {
    update: vi.fn(async (s: JobState, patch: Partial<JobState>) => ({ ...s, ...patch })),
    appendHistory: vi.fn(async (s: JobState) => s),
    fail: vi.fn(async (s: JobState) => ({ ...s, status: "failed" as const })),
    persist: vi.fn(async () => undefined),
    appendLineage: vi.fn(async () => undefined),
    appendInterruption: vi.fn(async () => undefined),
  };
}

function makeStoreFactory(mock: StoreMock) {
  return (_jobId: string) => mock as never;
}

// ---------------------------------------------------------------------------
// runtimeStrategy mock: real digestArtifacts that reads from disk
// ---------------------------------------------------------------------------

/**
 * Build a runtimeStrategy partial mock whose digestArtifacts reads each file
 * from `join(cwd, ref.path)` and computes sha256. Returns hash: null if the
 * file does not exist (matching LocalRuntime semantics).
 *
 * Used in TC-001 through TC-005, TC-010, TC-011.
 */
function makeRealDigestRuntimeStrategy() {
  return {
    digestArtifacts: async (
      refs: { path: string }[],
      cwd: string,
      _branch: string | null,
    ): Promise<ArtifactRef[]> => {
      const results: ArtifactRef[] = [];
      for (const ref of refs) {
        const absPath = path.join(cwd, ref.path);
        try {
          const content = await fs.readFile(absPath);
          const hex = sha256hex(content);
          results.push({ path: ref.path, hash: `sha256:${hex}` });
        } catch {
          results.push({ path: ref.path, hash: null });
        }
      }
      return results;
    },
  };
}

// ---------------------------------------------------------------------------
// PipelineDeps factory
// ---------------------------------------------------------------------------

function makeDeps(
  cwd: string,
  store: StoreMock,
  overrides: Partial<PipelineDeps> = {},
): PipelineDeps {
  return {
    cwd,
    slug: "example",
    config: {} as never,
    request: {
      type: "bug-fix",
      title: "Example",
      slug: "example",
      baseBranch: "main",
      content: "Example request",
      adr: false,
      path: "specrunner/changes/example/request.md",
    },
    dynamicContext: undefined,
    githubClient: {} as never,
    owner: "octo",
    repo: "repo",
    spawn: vi.fn() as never,
    storeFactory: makeStoreFactory(store),
    runner: {} as never,
    resumePrompt: undefined,
    resumeContext: undefined,
    runtimeStrategy: makeRealDigestRuntimeStrategy() as never,
    ...overrides,
  } as PipelineDeps;
}

// ---------------------------------------------------------------------------
// A: パス帰属（逐次）
// ---------------------------------------------------------------------------

describe("A: iteration-dependent path attribution — sequential (TC-001, TC-002, TC-010)", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "lao-seq-"));
    await fs.mkdir(path.join(tempDir, "out"), { recursive: true });
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it("TC-001: first attempt lineage outputs path ends in -001", async () => {
    // Write the file the first attempt will produce.
    const fileContent = "attempt-1";
    await fs.writeFile(path.join(tempDir, "out/result-001.md"), fileContent);

    const store = makeStoreMock();
    const events = new EventBus();
    const orchestrator = new CommitOrchestrator(makeStoreFactory(store), events);
    const step = makeIterStep();
    const state = makeState(); // steps: {} — no prior runs
    const deps = makeDeps(tempDir, store);
    const result = makeSuccessResult();

    await orchestrator.commitSuccess(step, state, deps, result);

    expect(store.appendLineage).toHaveBeenCalledOnce();
    const record = store.appendLineage.mock.calls[0]?.[0] as LineageRecord;
    expect(record).toBeDefined();
    expect(record.outputs).toHaveLength(1);
    // The path must end in -001 (the file actually written), not -002
    expect(record.outputs[0]?.path).toMatch(/result-001\.md$/);
  });

  it("TC-002: second attempt lineage outputs path ends in -002 (not -003)", async () => {
    // before this fix, the post-push state had length 2 → nextIteration=3 → path=-003 (missing) → hash=null
    // Write the file the second attempt will produce.
    const fileContent = "attempt-2";
    await fs.writeFile(path.join(tempDir, "out/result-002.md"), fileContent);

    const store = makeStoreMock();
    const events = new EventBus();
    const orchestrator = new CommitOrchestrator(makeStoreFactory(store), events);
    const step = makeIterStep();

    // State with one prior run already in steps["iter-step"]
    const stateWithOnePriorRun = makeState({
      steps: {
        "iter-step": [
          {
            attempt: 1,
            sessionId: null,
            outcome: {
              verdict: "approved" as Verdict,
              findingsPath: null,
              error: null,
            },
            startedAt: "2026-01-01T00:00:00.000Z",
            endedAt: "2026-01-01T00:01:00.000Z",
          },
        ],
      },
    });

    const deps = makeDeps(tempDir, store);
    const result = makeSuccessResult();

    await orchestrator.commitSuccess(step, stateWithOnePriorRun, deps, result);

    expect(store.appendLineage).toHaveBeenCalledOnce();
    const record = store.appendLineage.mock.calls[0]?.[0] as LineageRecord;
    expect(record).toBeDefined();
    expect(record.outputs).toHaveLength(1);
    // The path must end in -002 (the file actually written by the 2nd attempt), not -003
    expect(record.outputs[0]?.path).toMatch(/result-002\.md$/);
  });

  // TC-010 (should): 3rd attempt path is -003
  it("TC-010: third attempt lineage outputs path ends in -003", async () => {
    // Given same iteration-dependent step with 2 completed prior runs (state.steps[stepName].length === 2)
    const fileContent = "attempt-3";
    await fs.writeFile(path.join(tempDir, "out/result-003.md"), fileContent);

    const store = makeStoreMock();
    const events = new EventBus();
    const orchestrator = new CommitOrchestrator(makeStoreFactory(store), events);
    const step = makeIterStep();

    // State with two prior runs
    const stateWithTwoPriorRuns = makeState({
      steps: {
        "iter-step": [
          {
            attempt: 1,
            sessionId: null,
            outcome: { verdict: "approved" as Verdict, findingsPath: null, error: null },
            startedAt: "2026-01-01T00:00:00.000Z",
            endedAt: "2026-01-01T00:01:00.000Z",
          },
          {
            attempt: 2,
            sessionId: null,
            outcome: { verdict: "approved" as Verdict, findingsPath: null, error: null },
            startedAt: "2026-01-01T00:01:00.000Z",
            endedAt: "2026-01-01T00:02:00.000Z",
          },
        ],
      },
    });

    const deps = makeDeps(tempDir, store);
    const result = makeSuccessResult();

    await orchestrator.commitSuccess(step, stateWithTwoPriorRuns, deps, result);

    expect(store.appendLineage).toHaveBeenCalledOnce();
    const record = store.appendLineage.mock.calls[0]?.[0] as LineageRecord;
    expect(record).toBeDefined();
    expect(record.outputs).toHaveLength(1);
    expect(record.outputs[0]?.path).toMatch(/result-003\.md$/);
  });
});

// ---------------------------------------------------------------------------
// B: ハッシュ計算
// ---------------------------------------------------------------------------

describe("B: hash computation (TC-003, TC-004)", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "lao-hash-"));
    await fs.mkdir(path.join(tempDir, "out"), { recursive: true });
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it("TC-003: output file exists at correct (fixed) path → hash is sha256:<hex> (non-null)", async () => {
    // Scenario: output file exists at the correct iteration path
    const fileContent = "attempt-1 content for hash check";
    await fs.writeFile(path.join(tempDir, "out/result-001.md"), fileContent);

    const store = makeStoreMock();
    const events = new EventBus();
    const orchestrator = new CommitOrchestrator(makeStoreFactory(store), events);
    const step = makeIterStep();
    const state = makeState(); // no prior runs → writes() returns -001 path
    const deps = makeDeps(tempDir, store);
    const result = makeSuccessResult();

    await orchestrator.commitSuccess(step, state, deps, result);

    expect(store.appendLineage).toHaveBeenCalledOnce();
    const record = store.appendLineage.mock.calls[0]?.[0] as LineageRecord;
    const output = record.outputs[0];
    expect(output).toBeDefined();
    // Hash must be non-null and equal sha256 of the actual file content
    const expectedHash = `sha256:${sha256hex(fileContent)}`;
    expect(output?.hash).toBe(expectedHash);
    expect(output?.hash).not.toBeNull();
  });

  it("TC-004: optional input file does not exist → lineage inputs[i].hash is null", async () => {
    // Scenario: optional read (required: false) for a file that does not exist
    // Write the output file so appendLineage is triggered
    await fs.writeFile(path.join(tempDir, "out/result-001.md"), "some-output");

    const store = makeStoreMock();
    const events = new EventBus();
    const orchestrator = new CommitOrchestrator(makeStoreFactory(store), events);

    // Step that has both writes() and reads() — reads() declares an optional non-existent file
    const stepWithOptionalRead: AgentStep = {
      ...makeIterStep(),
      reads: (_state, _deps) => [
        {
          path: "inputs/optional-file.md",
          required: false,
        },
      ],
    };

    const state = makeState(); // no prior runs
    const deps = makeDeps(tempDir, store);
    const result = makeSuccessResult();

    await orchestrator.commitSuccess(stepWithOptionalRead, state, deps, result);

    expect(store.appendLineage).toHaveBeenCalledOnce();
    const record = store.appendLineage.mock.calls[0]?.[0] as LineageRecord;
    expect(record.inputs).toHaveLength(1);
    // File does not exist → hash must be null (best-effort, no error)
    expect(record.inputs[0]?.hash).toBeNull();
    // The required flag is preserved from reads()
    expect(record.inputs[0]?.required).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// C: 並列ラウンド
// ---------------------------------------------------------------------------

describe("C: parallel round path attribution (TC-005, TC-011)", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "lao-round-"));
    await fs.mkdir(path.join(tempDir, "out"), { recursive: true });
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it("TC-005: parallel round single member with 0 prior runs → lineage path ends in -001", async () => {
    // Scenario: parallel reviewer with iteration-dependent writes()
    // A single-member commitRound should attribute the correct -001 path
    const fileContent = "round-member-attempt-1";
    await fs.writeFile(path.join(tempDir, "out/result-001.md"), fileContent);

    const store = makeStoreMock();
    const events = new EventBus();
    const orchestrator = new CommitOrchestrator(makeStoreFactory(store), events);
    const step = makeIterStep();
    const state = makeState(); // no prior runs
    const deps = makeDeps(tempDir, store);

    const coordinatorRun = {
      attempt: 1,
      sessionId: null,
      outcome: { verdict: "approved" as const, findingsPath: null, error: null },
      startedAt: "2026-01-01T00:00:00.000Z",
      endedAt: "2026-01-01T00:01:00.000Z",
    };

    await orchestrator.commitRound({
      coordinatorName: "custom-reviewers",
      base: state,
      deps,
      members: [
        {
          step,
          startedAt: "2026-01-01T00:00:00.000Z",
          result: makeSuccessResult(),
        },
      ],
      reviewerStatuses: [],
      coordinatorRun,
      roundError: null,
    });

    expect(store.appendLineage).toHaveBeenCalledOnce();
    const record = store.appendLineage.mock.calls[0]?.[0] as LineageRecord;
    expect(record).toBeDefined();
    expect(record.outputs).toHaveLength(1);
    // Path must end in -001 (current attempt), not -002 (off-by-one from post-fold state)
    expect(record.outputs[0]?.path).toMatch(/result-001\.md$/);
    expect(record.outputs[0]?.hash).not.toBeNull();
  });

  // TC-011 (should): 2-member parallel round — fold order independence
  it("TC-011: 2-member parallel round — each member gets its own -001 path independently", async () => {
    // GIVEN 2 iteration-dependent steps (step-a, step-b), each with 0 prior runs
    // WHEN commitRound is called with both as members
    // THEN each member's lineage outputs path ends in its own -001 (fold order independent)
    await fs.mkdir(path.join(tempDir, "out-a"), { recursive: true });
    await fs.mkdir(path.join(tempDir, "out-b"), { recursive: true });

    const fileContentA = "step-a-attempt-1";
    const fileContentB = "step-b-attempt-1";

    // Build separate iteration steps with distinct names and output dirs
    const stepA: AgentStep = {
      kind: "agent",
      name: "step-a",
      agent: { id: "step-a-agent" } as never,
      buildMessage: () => "step-a message",
      resultFilePath: () => null,
      parseResult: () => ({ verdict: null, findingsPath: null }),
      writes: (state, _deps) => [
        { path: `out-a/result-${nextIteration(state, "step-a").toString().padStart(3, "0")}.md` },
      ],
    };

    const stepB: AgentStep = {
      kind: "agent",
      name: "step-b",
      agent: { id: "step-b-agent" } as never,
      buildMessage: () => "step-b message",
      resultFilePath: () => null,
      parseResult: () => ({ verdict: null, findingsPath: null }),
      writes: (state, _deps) => [
        { path: `out-b/result-${nextIteration(state, "step-b").toString().padStart(3, "0")}.md` },
      ],
    };

    await fs.writeFile(path.join(tempDir, "out-a/result-001.md"), fileContentA);
    await fs.writeFile(path.join(tempDir, "out-b/result-001.md"), fileContentB);

    const store = makeStoreMock();
    const events = new EventBus();
    const orchestrator = new CommitOrchestrator(makeStoreFactory(store), events);
    const state = makeState(); // both steps: 0 prior runs
    const deps = makeDeps(tempDir, store);

    const coordinatorRun = {
      attempt: 1,
      sessionId: null,
      outcome: { verdict: "approved" as const, findingsPath: null, error: null },
      startedAt: "2026-01-01T00:00:00.000Z",
      endedAt: "2026-01-01T00:01:00.000Z",
    };

    await orchestrator.commitRound({
      coordinatorName: "custom-reviewers",
      base: state,
      deps,
      members: [
        {
          step: stepA,
          startedAt: "2026-01-01T00:00:00.000Z",
          result: makeSuccessResult(makeCompletion("approved")),
        },
        {
          step: stepB,
          startedAt: "2026-01-01T00:00:01.000Z",
          result: makeSuccessResult(makeCompletion("approved")),
        },
      ],
      reviewerStatuses: [],
      coordinatorRun,
      roundError: null,
    });

    // appendLineage called once for step-a and once for step-b
    expect(store.appendLineage).toHaveBeenCalledTimes(2);

    const calls = store.appendLineage.mock.calls as [LineageRecord][];

    // Find each member's record by step name
    const recordA = calls.find((c) => c[0].step === "step-a")?.[0];
    const recordB = calls.find((c) => c[0].step === "step-b")?.[0];

    expect(recordA).toBeDefined();
    expect(recordB).toBeDefined();

    // step-a: path ends in -001 (not influenced by step-b's fold)
    expect(recordA?.outputs[0]?.path).toMatch(/out-a\/result-001\.md$/);
    // step-b: path ends in -001 (not influenced by step-a's fold)
    expect(recordB?.outputs[0]?.path).toMatch(/out-b\/result-001\.md$/);
  });
});

// ---------------------------------------------------------------------------
// D: 破壊確認
// ---------------------------------------------------------------------------

describe("D: destructive confirmation (TC-006)", () => {
  it("TC-006: evaluating writes() on the post-push state (pre-fix behavior) produces -002 path for first attempt", () => {
    // This test documents the PRE-FIX bug.
    // before this fix, the post-push state had length 1 → nextIteration=2 → path=-002 (missing) → hash=null
    //
    // The fix is: evaluate writes() on the PRE-push state (before projectSuccess appends the StepRun).
    // This test verifies the math: nextIteration on post-push state gives N+1 (wrong), not N (correct).

    const baseState = makeState(); // no prior runs: state.steps = {}
    const step = makeIterStep();

    // Evaluate writes() on the PRE-push state → this is what the FIX does
    const writesOnPrePush = step.writes!(baseState, {} as never);
    // nextIteration(baseState, "iter-step") = (steps["iter-step"]?.length ?? 0) + 1 = 0 + 1 = 1
    expect(writesOnPrePush[0]?.path).toMatch(/result-001\.md$/);

    // Simulate what the buggy code did: evaluate writes() on the post-push state
    // (a state where the new StepRun has already been appended by pushStepResult)
    const postPushState: JobState = {
      ...baseState,
      steps: {
        "iter-step": [
          {
            attempt: 1,
            sessionId: null,
            outcome: {
              verdict: "approved" as Verdict,
              findingsPath: null,
              error: null,
            },
            startedAt: "2026-01-01T00:00:00.000Z",
            endedAt: "2026-01-01T00:01:00.000Z",
          },
        ],
      },
    };

    const writesOnPostPush = step.writes!(postPushState, {} as never);
    // nextIteration(postPushState, "iter-step") = (steps["iter-step"]?.length ?? 0) + 1 = 1 + 1 = 2
    // → path = -002 (the WRONG path — file doesn't exist, so hash would be null)
    expect(writesOnPostPush[0]?.path).toMatch(/result-002\.md$/);

    // This confirms: TC-001 would fail with pre-fix code because the recorded path
    // ends in -002, not -001. The fix moves writes() evaluation before projectSuccess.
  });
});

// ---------------------------------------------------------------------------
// E: 後方互換
// ---------------------------------------------------------------------------

describe("E: backward compat (TC-007)", () => {
  it("TC-007: step without writes() → appendLineage is never called", async () => {
    // GIVEN step.writes is undefined (a step that declares no write outputs)
    // WHEN applySuccessPostPersistEffects receives preWriteIo === []
    // THEN store.appendLineage is not called (guard condition: preWriteIo.length > 0)
    const store = makeStoreMock();
    const events = new EventBus();
    const orchestrator = new CommitOrchestrator(makeStoreFactory(store), events);

    // Step with no writes() — e.g. implementer, build-fixer (they don't declare outputs)
    const stepNoWrites: AgentStep = {
      kind: "agent",
      name: "no-writes-step",
      agent: { id: "no-writes-agent" } as never,
      buildMessage: () => "message",
      resultFilePath: () => null,
      parseResult: () => ({ verdict: null, findingsPath: null }),
      // writes is intentionally absent
    };

    const state = makeState();
    // Include runtimeStrategy so the guard check is reached
    const deps = makeDeps("/tmp", store);
    const result = makeSuccessResult();

    await orchestrator.commitSuccess(stepNoWrites, state, deps, result);

    // appendLineage must NOT be called when the step has no writes()
    expect(store.appendLineage).not.toHaveBeenCalled();
  });
});
